---
name: zizmor

'on':
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - .github/dependabot.yml
  pull_request:
    paths:
      - .github/workflows/**
      - .github/dependabot.yml
  workflow_dispatch:
  schedule:
    - cron: '23 5 * * 1'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze workflows
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read # Check out repository workflows for static analysis.
      security-events: write # Upload Zizmor SARIF results to code scanning.
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8
        with:
          inputs: |
            .github/workflows
            .github/dependabot.yml
